### ISSUE TITLE
Open File's Filename Somewhere Besides Summary Tab

### ISSUE THREAD

**Issue by JeridInsight** [tabulartools/pbi-explorer#5]
### The feature request

It would be really nice if the full path of the file that is currently being examined was shown somewhere, like at the bottom right of the interface.  When you're live connected, PBI shows which model your connected to on the thin strip at the bottom.  The full path is helpful, because the Summary tab only shows the filename, and often we have files named the same thing in different directories. 

### Proposed solution

Add the full file path of the file being actively "inspected" at the bottom right of the interface.  Also, maybe a hover-over on the file name in the Summary tab that shows the full path.  One or the other, or maybe both?  : )

**Comment by DBojsen** [comment]
Hi @JeridInsight 

Makes a lot of sense.  We'll add that.

BR David - Tabular Tools

**Comment by DBojsen** [comment]
This have been implemented in version 0.3.1 (Beta2).  Please update by downloading the new version at www.PBIExplorer.com.
Thanks for reporting.

You'll need to hover over the filename to see the full path (due to lack of space):
![image](https://github.com/tabulartools/pbi-explorer/assets/22237520/188bc03c-05d8-4b90-9ecd-739154f89aab)

**Comment by JeridInsight** [comment]
Looks great.  I tested it and it works well.  : )
