### ISSUE TITLE
Powerbi Exporer doesn't show all measures

### ISSUE THREAD

**Issue by JNTheunissen** [tabulartools/pbi-explorer#51]
### Describe the problem

The datamodeller tab is empty, doesn't show any items.
The Powerbi file exists of tabels only, there is one default page present but not used.

In other files with pages the measures are shown but less then there are in the file.

The measures shown are not grouped by the "display folder" value.
The display folders are not shown at  all, would be very nice. :-)

 

### PBI Explorer

4.1

### Power BI

Version: 2.122.746.0 64-bit (October 2023)

### Windows

Windows 11 Enterprise

**Comment by DBojsen** [comment]
Hi @JNTheunissen 

The data model shown is an inferred/conceptual model maintained by the report layer in a Power BI Report.
It *only* contains the tables, columns, hierarchies and measures that is in use by report elements.
**And** it doesn't have information about the display folder, format string etc.

So what you are seeing is by design.

We expect to at some point in time show the full data model if you open a "thick" report which includes the data model elements, but "thin" reports that connect to a remote data model will probably stay like this forever.

**Comment by fernandocalero** [comment]
But the FactOnlineSales table is in use and has the main column used for the Sales measure. I don't get it why it's not shown in the Data Model Explorer. 🤔
